services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  musetalk-python:
    build:
      context: .
      dockerfile: MuseTalkEngine/Dockerfile
    container_name: musetalk-python
    # 关键：添加nvidia runtime让容器能访问GPU
    runtime: nvidia
    environment:
      # GPU访问配置
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # 路径配置
      - MUSE_MODELS_DIR=/opt/musetalk/models
      - MUSE_VIDEOS_DIR=/videos
      - MUSE_TEMP_DIR=/temp
      - MUSE_TALK_DIR=/opt/musetalk/repo/MuseTalk
    volumes:
      - ./MuseTalkEngine:/opt/musetalk/repo/MuseTalkEngine
      - ./MuseTalk:/opt/musetalk/repo/MuseTalk
      - ./LmyDigitalHuman:/opt/musetalk/repo/LmyDigitalHuman
      # 关键：将模型目录挂载到MuseTalk期望的位置
      - /opt/musetalk/models:/opt/musetalk/repo/MuseTalk/models
      # 模板预处理缓存目录
      - /opt/musetalk/models:/opt/musetalk/models
      - /opt/musetalk/videos:/videos
      - /opt/musetalk/temp:/temp
    working_dir: /opt/musetalk/repo/MuseTalkEngine
    # 需要主机已安装 nvidia-container-toolkit
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - web
    restart: unless-stopped

  lmy-digitalhuman:
    build:
      context: .
      dockerfile: LmyDigitalHuman/Dockerfile
    container_name: lmy-digitalhuman
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - musetalk-python
    volumes:
      - ./LmyDigitalHuman:/opt/musetalk/repo/LmyDigitalHuman
      # 模板预处理缓存目录（C#端需要访问）
      - /opt/musetalk/models:/opt/musetalk/models
      - /opt/musetalk/videos:/videos
      - /opt/musetalk/temp:/temp
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.lmy-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.lmy-web.entrypoints=web"
      - "traefik.http.routers.lmy-web.middlewares=https-redirect"
      - "traefik.http.routers.lmy-websecure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.lmy-websecure.entrypoints=websecure"
      - "traefik.http.routers.lmy-websecure.tls=true"
      - "traefik.http.routers.lmy-websecure.tls.certresolver=myresolver"
      - "traefik.http.services.lmy.loadbalancer.server.port=5000"
    restart: unless-stopped

networks:
  web:
    external: false