version: "3.9"

services:
  # 为本地开发和测试暴露端口
  musetalk-python:
    ports:
      - "28888:28888"

  lmy-digitalhuman:
    # 暴露端口以便从主机访问
    ports:
      - "5000:5000"
    # 如果不需要Traefik，可以清空labels
    # labels: []

  # 如果不需要Traefik，可以停止它
  # traefik:
  #   deploy:
  #     replicas: 0