version: '3.8'

services:
  musetalk:
    build: .
    image: musetalk:latest
    container_name: musetalk
    runtime: nvidia
    environment:
      - RUN_MODE=${RUN_MODE:-gradio}
      - CUDA_VISIBLE_DEVICES=${GPU_IDS:-all}
      - BATCH_SIZE=${BATCH_SIZE:-auto}
    volumes:
      - ./models:/app/models
      - ./inputs:/app/inputs  
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    ports:
      - "7860:7860"
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all