version: '3.8'

services:
  # 数字人主服务
  digitalhuman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lmy-digitalhuman
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
      # 连接到宿主机上的Ollama服务
      - Ollama__BaseUrl=http://host.docker.internal:11434
    volumes:
      # 持久化存储用户上传的模板和生成的视频
      - ./data/templates:/app/wwwroot/templates
      - ./data/videos:/app/wwwroot/videos
      - ./data/temp:/app/temp
      - ./data/logs:/app/logs
      # 如果有预训练模型，可以挂载到容器中
      - ./models:/app/models
    networks:
      - digitalhuman-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  digitalhuman-network:
    driver: bridge

volumes:
  digitalhuman_data:
    driver: local