# MuseTalk实时性能优化配置
# 基于官方realtime.yaml，针对RTX 4090x4优化

# 任务配置 - 将由C#动态替换
task_001:
  video_path: "placeholder_video.jpg"
  audio_path: "placeholder_audio.wav"
  bbox_shift: 0
  result_name: "output.mp4"

# 模型配置
model:
  unet_config: "models/musetalk/musetalk.json"
  unet_model_path: "models/musetalk/pytorch_model.bin"
  whisper_dir: "models/whisper"
  vae_type: "sd-vae"

# 性能优化配置
performance:
  # GPU配置
  gpu_id: [0, 1, 2, 3]  # 使用所有GPU
  batch_size: 8         # 大批处理
  use_float16: true     # FP16精度
  
  # 并行配置
  num_workers: 8        # 数据加载线程
  prefetch_factor: 4    # 预取因子
  
  # 内存优化
  pin_memory: true      # 锁页内存
  non_blocking: true    # 非阻塞传输
  
  # 编译优化
  torch_compile: true   # 启用torch.compile
  compile_mode: "max-autotune"  # 最大自动调优

# 质量配置
quality:
  fps: 25
  resolution: 256
  version: "v1"
  
  # 跳过不必要的步骤以提升速度
  skip_save_images: true    # 不保存中间图片
  skip_face_parsing: false  # 保留面部解析以确保质量
  
# 缓存配置
cache:
  enable_model_cache: true     # 启用模型缓存
  enable_result_cache: true    # 启用结果缓存
  cache_size_limit: 1000       # 缓存条目限制
  
# 实时优化
realtime:
  enable_streaming: false      # 流式处理（如果支持）
  low_latency_mode: true       # 低延迟模式
  adaptive_batch_size: true    # 自适应批处理大小
  
# 调试配置
debug:
  profile_inference: false     # 性能分析
  log_memory_usage: false      # 内存使用日志
  benchmark_mode: false        # 基准测试模式